package com.aaax.core.constant.enu;

import com.aaax.core.exception.BizException;
import com.aaax.core.response.SystemResponse;

import java.util.Arrays;

public enum Country {
    AFGHANISTAN("+93", "AF"),
    ALBANIA("+355", "AL"),
    ALGERIA("+213", "DZ"),
    ANDORRA("+376", "AD"),
    ANGOLA("+244", "AO"),
    ARGENTINA("+54", "AR"),
    ARMENIA("+374", "AM"),
    AUSTRALIA("+61", "AU"),
    AUSTRIA("+43", "AT"),
    AZERBAIJAN("+994", "AZ"),
    BAHRAIN("+973", "BH"),
    BANGLADESH("+880", "BD"),
    BARBADOS("+1-246", "BB"),
    BELARUS("+375", "BY"),
    BELGIUM("+32", "BE"),
    BELIZE("+501", "BZ"),
    BENIN("+229", "BJ"),
    BHUTAN("+975", "BT"),
    BOLIVIA("+591", "BO"),
    BOSNIA_AND_HERZEGOVINA("+387", "BA"),
    BOTSWANA("+267", "BW"),
    BRAZIL("+55", "BR"),
    BRUNEI("+673", "BN"),
    BULGARIA("+359", "BG"),
    BURKINA_FASO("+226", "BF"),
    BURUNDI("+257", "BI"),
    CABO_VERDE("+238", "CV"),
    CAMBODIA("+855", "KH"),
    CAMEROON("+237", "CM"),
    CANADA("+1", "CA"),
    CENTRAL_AFRICAN_REPUBLIC("+236", "CF"),
    CHAD("+235", "TD"),
    CHILE("+56", "CL"),
    CHINA("+86", "CN"),
    COLOMBIA("+57", "CO"),
    COMOROS("+269", "KM"),
    CONGO("+242", "CG"),
    COSTA_RICA("+506", "CR"),
    CROATIA("+385", "HR"),
    CUBA("+53", "CU"),
    CYPRUS("+357", "CY"),
    CZECH_REPUBLIC("+420", "CZ"),
    DENMARK("+45", "DK"),
    DJIBOUTI("+253", "DJ"),
    DOMINICA("+1-767", "DM"),
    DOMINICAN_REPUBLIC("+1-809", "DO"),
    ECUADOR("+593", "EC"),
    EGYPT("+20", "EG"),
    EL_SALVADOR("+503", "SV"),
    EQUATORIAL_GUINEA("+240", "GQ"),
    ERITREA("+291", "ER"),
    ESTONIA("+372", "EE"),
    ESWATINI("+268", "SZ"),
    ETHIOPIA("+251", "ET"),
    FIJI("+679", "FJ"),
    FINLAND("+358", "FI"),
    FRANCE("+33", "FR"),
    GABON("+241", "GA"),
    GAMBIA("+220", "GM"),
    GEORGIA("+995", "GE"),
    GERMANY("+49", "DE"),
    GHANA("+233", "GH"),
    GREECE("+30", "GR"),
    GRENADA("+1-473", "GD"),
    GUATEMALA("+502", "GT"),
    GUINEA("+224", "GN"),
    GUINEA_BISSAU("+245", "GW"),
    GUYANA("+592", "GY"),
    HAITI("+509", "HT"),
    HONDURAS("+504", "HN"),
    HONG_KONG("+852", "HK"),
    HUNGARY("+36", "HU"),
    ICELAND("+354", "IS"),
    INDIA("+91", "IN"),
    INDONESIA("+62", "ID"),
    IRAN("+98", "IR"),
    IRAQ("+964", "IQ"),
    IRELAND("+353", "IE"),
    ISRAEL("+972", "IL"),
    ITALY("+39", "IT"),
    JAMAICA("+1-876", "JM"),
    JAPAN("+81", "JP"),
    JORDAN("+962", "JO"),
    KAZAKHSTAN("+7", "KZ"),
    KENYA("+254", "KE"),
    KIRIBATI("+686", "KI"),
    KOSOVO("+383", "XK"),
    KUWAIT("+965", "KW"),
    KYRGYZSTAN("+996", "KG"),
    LAOS("+856", "LA"),
    LATVIA("+371", "LV"),
    LEBANON("+961", "LB"),
    LESOTHO("+266", "LS"),
    LIBERIA("+231", "LR"),
    LIBYA("+218", "LY"),
    LIECHTENSTEIN("+423", "LI"),
    LITHUANIA("+370", "LT"),
    LUXEMBOURG("+352", "LU"),
    MADAGASCAR("+261", "MG"),
    MALAWI("+265", "MW"),
    MALAYSIA("+60", "MY"),
    MALDIVES("+960", "MV"),
    MALI("+223", "ML"),
    MALTA("+356", "MT"),
    MAURITANIA("+222", "MR"),
    MAURITIUS("+230", "MU"),
    MEXICO("+52", "MX"),
    MICRONESIA("+691", "FM"),
    MOLDOVA("+373", "MD"),
    MONACO("+377", "MC"),
    MONGOLIA("+976", "MN"),
    MONTENEGRO("+382", "ME"),
    MOROCCO("+212", "MA"),
    MOZAMBIQUE("+258", "MZ"),
    NAMIBIA("+264", "NA"),
    NAURU("+674", "NR"),
    NEPAL("+977", "NP"),
    NETHERLANDS("+31", "NL"),
    NEW_ZEALAND("+64", "NZ"),
    NICARAGUA("+505", "NI"),
    NIGER("+227", "NE"),
    NIGERIA("+234", "NG"),
    NORTH_MACEDONIA("+389", "MK"),
    NORWAY("+47", "NO"),
    OMAN("+968", "OM"),
    PAKISTAN("+92", "PK"),
    PALAU("+680", "PW"),
    PANAMA("+507", "PA"),
    PAPUA_NEW_GUINEA("+675", "PG"),
    PARAGUAY("+595", "PY"),
    PERU("+51", "PE"),
    PHILIPPINES("+63", "PH"),
    POLAND("+48", "PL"),
    PORTUGAL("+351", "PT"),
    QATAR("+974", "QA"),
    ROMANIA("+40", "RO"),
    RUSSIA("+7", "RU"),
    RWANDA("+250", "RW"),
    SAINT_KITTS_AND_NEVIS("+1-869", "KN"),
    SAINT_LUCIA("+1-758", "LC"),
    SAINT_VINCENT_AND_THE_GRENADINES("+1-784", "VC"),
    SAMOA("+685", "WS"),
    SAN_MARINO("+378", "SM"),
    SAO_TOME_AND_PRINCIPE("+239", "ST"),
    SAUDI_ARABIA("+966", "SA"),
    SENEGAL("+221", "SN"),
    SERBIA("+381", "RS"),
    SEYCHELLES("+248", "SC"),
    SIERRA_LEONE("+232", "SL"),
    SINGAPORE("+65", "SG"),
    SLOVAKIA("+421", "SK"),
    SLOVENIA("+386", "SI"),
    SOLOMON_ISLANDS("+677", "SB"),
    SOMALIA("+252", "SO"),
    SOUTH_AFRICA("+27", "ZA"),
    SOUTH_KOREA("+82", "KR"),
    SOUTH_SUDAN("+211", "SS"),
    SPAIN("+34", "ES"),
    SRI_LANKA("+94", "LK"),
    SUDAN("+249", "SD"),
    SURINAME("+597", "SR"),
    SWEDEN("+46", "SE"),
    SWITZERLAND("+41", "CH"),
    SYRIA("+963", "SY"),
    TAIWAN("+886", "TW"),
    TAJIKISTAN("+992", "TJ"),
    TANZANIA("+255", "TZ"),
    THAILAND("+66", "TH"),
    TOGO("+228", "TG"),
    TONGA("+676", "TO"),
    TRINIDAD_AND_TOBAGO("+1-868", "TT"),
    TUNISIA("+216", "TN"),
    TURKMENISTAN("+993", "TM"),
    TURKEY("+90", "TR"),
    TUVALU("+688", "TV"),
    UGANDA("+256", "UG"),
    UKRAINE("+380", "UA"),
    UNITED_ARAB_EMIRATES("+971", "AE"),
    UNITED_KINGDOM("+44", "GB"),
    UNITED_STATES("+1", "US"),
    URUGUAY("+598", "UY"),
    UZBEKISTAN("+998", "UZ"),
    VANUATU("+678", "VU"),
    VATICAN_CITY("+39", "VA"),
    VENEZUELA("+58", "VE"),
    VIETNAM("+84", "VN"),
    YEMEN("+967", "YE"),
    ZAMBIA("+260", "ZM"),
    ZIMBABWE("+263", "ZW");



    private final String areaCode;
    private final String shortForm;

    Country(String areaCode, String shortForm) {
        this.areaCode = areaCode;
        this.shortForm = shortForm;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public String getShortForm() {
        return shortForm;
    }

    public static Country get(String code) {
        for (Country value : Country.values()) {
            if (code.equalsIgnoreCase(value.shortForm)){
                return value;
            }
        }
        String message = String.format("Wrong [%s] value. [%s] not in-> %s", code, code, Arrays.asList(Country.values()));
        throw new BizException(SystemResponse.PAM0400, message);
    }
}
